import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/admin";
import { DayCard } from "@/app/player/meal-card";
import type { Academy, MealPlan, Player } from "@/lib/types";

// This page is PUBLIC — no login. A player opens it with their secret link.
// It uses the service-role client (bypasses RLS) and finds the player ONLY by
// their unguessable access_token, so no other player's data is reachable.
// Always read fresh from the DB so a regenerated plan shows up immediately.
export const dynamic = "force-dynamic";

export default async function PlayerPlanPage(
  props: PageProps<"/player/[access_token]">,
) {
  const { access_token } = await props.params;

  const supabase = createAdminClient();

  const { data: player } = await supabase
    .from("players")
    .select("*")
    .eq("access_token", access_token)
    .maybeSingle<Player>();

  // Unknown/invalid token: show the standard 404, never reveal whether the
  // token "exists but has no plan" vs "doesn't exist".
  if (!player) notFound();

  const [{ data: mealPlan }, { data: academy }] = await Promise.all([
    supabase
      .from("meal_plans")
      .select("*")
      .eq("player_id", player.id)
      .maybeSingle<MealPlan>(),
    supabase
      .from("academies")
      .select("*")
      .eq("id", player.academy_id)
      .maybeSingle<Academy>(),
  ]);

  const days = mealPlan?.plan_json?.days ?? [];

  return (
    <main className="min-h-screen bg-slate-100">
      <header className="bg-emerald-800 px-5 py-6 text-white">
        <p className="text-sm font-semibold uppercase tracking-widest text-emerald-200">
          Taqa Nutrition Plan
        </p>
        <h1 className="mt-1 text-3xl font-extrabold">{player.name}</h1>
        <p className="mt-1 text-base text-emerald-100">
          {academy?.name}
          {academy?.sport_type ? ` · ${academy.sport_type}` : ""}
        </p>
      </header>

      <div className="mx-auto max-w-md space-y-4 px-4 py-6">
        {days.length === 0 ? (
          <div className="rounded-2xl border border-slate-200 bg-white px-5 py-10 text-center shadow-sm">
            <p className="text-lg font-bold text-slate-900">
              No plan yet
            </p>
            <p className="mt-1 text-base text-slate-600">
              Your meal plan hasn&apos;t been created yet. Please check back
              soon.
            </p>
          </div>
        ) : (
          days.map((day) => <DayCard key={day.day} day={day} />)
        )}
      </div>

      <footer className="px-5 pb-8 pt-2 text-center text-sm text-slate-500">
        Generated by Taqa · Eat for your training
      </footer>
    </main>
  );
}
